.PHONY: validate
validate: ## Run all validation checks
	@go fmt ./...
	@go vet ./...
	@golangci-lint run ./...
	@go test -race ./...

.PHONY: help
help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "%-15s %s\n", $$1, $$2}'